- name: reboot
  shell: reboot
  async: 0
  poll: 0
  notify: wait for host

- name: wait for host
  delegate_to: localhost
  wait_for:
    host: {{ ansible_ssh_host }}
    port: {{ ansible_ssh_port }}
    state: started
    timeout: {{ reboot_timeout }}