- name: reboot
  shell: shutdown -r now
  async: 0
  poll: 0
  notify: wait
  ignore_errors: yes

- name: wait
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_ssh_host }}"
    port: "{{ ansible_ssh_port }}"
    state: started
    timeout: "{{ reboot_timeout }}"
  when:
  - wait_for_host_after_reboot