# smartos repo url
SmartOSRepoURL: "https://pkgsrc.joyent.com/packages/SmartOS/"

# get the smartos repo page and set latest repo
grepline: "egrep '20[0-9]{2}Q[0-9]{1}' | tail -1 | awk -F '[<>]' '{print $3}' | tr -d '/'"
repo_html: "{{ lookup('url',SmartOSRepoURL,split_lines=False) }}"
SmartOSRepo: "{{ lookup('pipe','curl ' + SmartOSRepoURL + grepline) }}"

pkginReposConf: "/opt/local/etc/pkgin/repositories.conf"
reposLine: "{{ SmartOSRepoURL }}{{ SmartOSRepo }}/x86_64/All"
